name: Documentation

on:
  pull_request:
    branches:
      - master

jobs:
  builds:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Launch
        run: ./.github/scripts/doc.sh
        shell: bash
